#!/bin/bash
if [ $# -ne 2 ]
then
  echo "./switch_org <token> <user_id>"
  echo "Deactivate a user, unassign their shifts and delete their tasks."
  exit 1
fi
data="[{\"id\": $2, \"active\": false}]"
SERVER=${SERVER:=api}
curl "https://$SERVER.getsling.com/users?shifts=unassign&tasks=delete" \
  -X PUT \
  -d "$data" \
  -H "Content-Type: application/json" \
  -H "Authorization: ${1//[$'\t\r\n ']}" \
  -H "accept: */*"
