#!/bin/bash
if [ $# -ne 2 ]
then
  echo "./login <email> <password>"
  echo "Returns an Authorization token."
  exit 1
fi
SERVER=${SERVER:=api}
curl -is "https://$SERVER.getsling.com/account/login" \
  -X POST \
  -d "{\"email\": \"$1\",\"password\": \"$2\"}" \
  -H "Content-Type: application/json" \
  -H "accept: */*" | \
  grep "^authorization: " | \
  sed "s/^authorization: //"
