#!/bin/bash

# Validate arguments.
if [ $# -ne 3 ]
then
  echo "./csv2shifts <email> <password> <csv>"
  echo "csv format: start,end,location name,position name,email"
  exit 1
fi
SERVER=${SERVER:=api}

# Login.
token=$(
  curl -is "https://$SERVER.getsling.com/account/login" \
    -X POST \
    -d "{\"email\": \"$1\",\"password\": \"$2\"}" \
    -H "Content-Type: application/json" \
    -H "accept: */*" | \
  grep "^authorization: " | \
  sed "s/^authorization: //"

)

# Get a concise description of positions and locations.
groups=$(
  curl -Gs "https://$SERVER.getsling.com/users/concise" \
    -H "Authorization: ${token//[$'\t\r\n ']}" \
    -H "accept: */*"
)

# Parse out location and position lookups.
filter='
  .groups |
  to_entries |
  map(.value) |
  map(select(.type == "type-value")) |
  map({name, id})
'
type="s/type-value/location/"
locations=$(echo $groups | jq $(echo ${filter//[$'\t\r\n ']} | sed "$type"))
type="s/type-value/position/"
positions=$(echo $groups | jq $(echo ${filter//[$'\t\r\n ']} | sed "$type"))

# Parse out users.
filter='
  .users |
  to_entries |
  map(.value) |
  map({email, id})
'
users=$(echo $groups | jq ${filter//[$'\t\r\n ']})

# Used to template a shift.
shift='
,{
  "dtstart": "dtstart-value",
  "dtend": "dtend-value",
  "location": { "id": location-value },
  "position": { "id": position-value },
  "user": { "id": user-value }
}
'

# Parse the csv.
results=""
while IFS=, read -r dtstart dtend location position email
do
  # Lookup IDs.
  location_id=$(
    echo $locations |
    jq "map(select(.name == \"$location\")) | .[0].id"
  )
  position_id=$(
    echo $positions |
    jq "map(select(.name == \"$position\")) | .[0].id"
  )
  user_id=$(
    echo $users |
    jq "map(select(.email == \"$email\")) | .[0].id"
  )

  # Construct the response.
  results+=$(
    echo $shift |
    sed "s/dtstart-value/$dtstart/" |
    sed "s/dtend-value/$dtend/" |
    sed "s/location-value/$location_id/" |
    sed "s/position-value/$position_id/" |
    sed "s/user-value/$user_id/"
  )
done < $3

# Upload the shifts.
body="[${results:1}]"
curl "https://$SERVER.getsling.com/shifts/bulk" \
  -X POST \
  -d "${body//[$'\t\r\n ']}" \
  -H "Content-Type: application/json" \
  -H "Authorization: ${token//[$'\t\r\n ']}" \
  -H "accept: */*"
