#!/bin/bash
set -e

# Validate arguments.
if [ $# -ne 2 ]
then
  echo "./csv2shifts <token> <csv>"
  echo "csv format: start,end,location name,position name,email"
  exit 1
fi
SERVER=${SERVER:=api}

# Check for jq.
command -v jq >/dev/null 2>&1 || {
  echo >&2 "jq is required but not installed."
  exit 1
}

# Get a concise description of positions and locations.
groups=$(
  curl -Gs "https://$SERVER.getsling.com/users/concise" \
    -H "Authorization: $1" \
    -H "accept: */*"
)

# Parse out location and position lookups.
filter='
  .groups |
  to_entries |
  map(.value) |
  map(select(.type == "type-value")) |
  map({name, id})
'
type="s/type-value/location/"
locations=$(echo $groups | jq $(echo ${filter//[$'\t\r\n ']} | sed "$type"))
type="s/type-value/position/"
positions=$(echo $groups | jq $(echo ${filter//[$'\t\r\n ']} | sed "$type"))

# Parse out users.
filter='
  .users |
  to_entries |
  map(.value) |
  map({email, id})
'
users=$(echo $groups | jq ${filter//[$'\t\r\n ']})

# Used to template a shift.
shift='
,{
  "dtstart": "dtstart-value",
  "dtend": "dtend-value",
  "location": { "id": location-value },
  "position": { "id": position-value },
  "user": { "id": user-value }
}
'

# Parse the csv.
results=""
while IFS=, read -r dtstart dtend location position email
do
  # Lookup IDs.
  location_id=$(
    echo $locations |
    jq "map(select(.name == \"$location\")) | .[0].id"
  )
  position_id=$(
    echo $positions |
    jq "map(select(.name == \"$position\")) | .[0].id"
  )
  user_id=$(
    echo $users |
    jq "map(select(.email == \"$email\")) | .[0].id"
  )

  # Construct the response.
  results+=$(
    echo $shift |
    sed "s/dtstart-value/$dtstart/" |
    sed "s/dtend-value/$dtend/" |
    sed "s/location-value/$location_id/" |
    sed "s/position-value/$position_id/" |
    sed "s/user-value/$user_id/"
  )
done < $2

# Upload the shifts.
body="[${results:1}]"
curl "https://$SERVER.getsling.com/shifts/bulk" \
  -X POST \
  -d "${body//[$'\t\r\n ']}" \
  -H "Content-Type: application/json" \
  -H "Authorization: $1" \
  -H "accept: */*"
